# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/matt-larsen-sld/freshservice-helper"

[version]
current = "0.0.8"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = ".bumpversion.cfg"

[[file]]
src = "setup.py"

[[file]]
src = "src/fshelper/__init__.py"

[[file]]
src = "README.md"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
name = "check release notes"
cmd = "grep -q {new_version} RELEASE_NOTES.md"

[[before_commit]]
name = "black"
cmd = "black src tests functional_tests"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
